Feature/bot 3322 coach coach worker   use redis
codeforequity-at/botium-coach-worker pull request #11
Opened 2022-10-18 11:58 UTC by murliwatz

2022-10-24 15:13 UTC, codeforequity-at requested changes

2022-10-24 15:13 UTC, codeforequity-at commented on main.py
> +    red = redis.Redis(host=os.environ.get('REDIS_HOST', 'localhost'), port=6379, db=os.environ.get('REDIS_DB', 0))
will this work for clustered Redis ?

2022-10-25 08:07 UTC, codeforequity-at commented on main.py
> +                        "status": ['Request for for chi2 analysis is queued']
Can we use "status" as a code/enum and place this in an additional field "statusDescription"
Also, an additional status can be "calculations running", maybe even with some kind of progress - not as percentage, but maybe as "step 3/5 completed ..."

2022-11-04 06:59 UTC, murliwatz commented on main.py
> +    red = redis.Redis(host=os.environ.get('REDIS_HOST', 'localhost'), port=6379, db=0)
done

2022-11-04 06:59 UTC, murliwatz commented on main.py
> +    red = redis.Redis(host=os.environ.get('REDIS_HOST', 'localhost'), port=6379, db=os.environ.get('REDIS_DB', 0))
added sentinel support

2022-11-04 07:00 UTC, murliwatz commented on main.py
> +                        "status": ['Request for for chi2 analysis is queued']
changed status update functionality

2022-11-04 07:00 UTC, murliwatz commented on main.py
> +                    red.set('coachworker_status_chi2_' + req_obj['coachSessionId'], json.dumps({
redis keys expire now

2022-11-04 07:51 UTC, merged